### ISSUE TITLE
Unable to find Reg in Image

### ISSUE THREAD

**Issue by TomParagon** [iMicknl/cordova-plugin-openalpr#16]
Hi  

I am using the Telerik Platform and have successfully plugged in the Cordova control.

I have changed line 74 of the file OpenALPR.java to use the "gb" type of filtering however the array comes back empty?

![1498467368998 1](https://user-images.githubusercontent.com/17740912/27533775-bc1e93ba-5a5c-11e7-9655-fca85adf1380.jpg)

Hope you have time to help

regards

Tom Williams

**Comment by TomParagon** [comment]
Ok Solved it, despite the photo looking the correct orientation on the phone, the image was taken in portrait not landscape this was only obvious when I attached the image to this bug!

**Comment by iMicknl** [comment]
Nice to hear that you solved it already, @TomParagon.
