### ISSUE TITLE
ionic3 usage example?

### ISSUE THREAD

**Issue by vmanchev** [iMicknl/cordova-plugin-openalpr#17]
Hi, thanks for the effort you put to bring OpenALPR as Cordova plugin. 

I'm having a problem using it with an Ionic 3 application. The given example is for Ionic 1, but now we are expect to import classes from packages, and I have no idea how to do it with OpenALPR. A short example or at least some directions, will be highly appreciated.

**Comment by iMicknl** [comment]
I will have a look next week, @vmanchev! I don't have any experience with Ionic 3, however I have experience using Typescript. Maybe a few changes to this package will be necessary.

**Comment by melvinversluijs** [comment]
@vmanchev,
An Ionic 3 sample has been added to the readme, we've also created a sample project which is accessible through the following repository: https://github.com/melvinversluijs/ionic3-sample
