### ISSUE TITLE
Is it possible to use this in phonegap? 

### ISSUE THREAD

**Issue by CyrisXD** [iMicknl/cordova-plugin-openalpr#19]
Hi there, 

How would I implement this into PhoneGap? 
Do I need to include the JS file in the Index.html? 

I'm having trouble actually calling the function from my index.js file, it doesn't seem to do anything. No errors, no output.

**Comment by CyrisXD** [comment]
Alright, I believe I've gotten this working. Didn't realize it wouldn't work on the PhoneGap app preview. You have to build the APK and run `Cordova Run Android` with your Android attached via USB. 

I've managed to run the function, and inserted the image path. However the data returned is just an empty array? Any idea why? 

Cheers

**Comment by melvinversluijs** [comment]
Hi @CyrisXD,

Could you provide us with some more information? I assume you took a photo of a license plate (Or used an existing one) to test this?

1. Which country's license plate did you use? 
2. Did you try to get closer to the license plate or try different angles to check for different results?

Furthermore you could try debugging this with the `adb logcat` command. This will give you more specific information on what is going on while running the app on your Android phone.

Cheers,
Melvin

**Comment by iMicknl** [comment]
**Closed because of inactivity**
