### ISSUE TITLE
Library not supported

### ISSUE THREAD

**Issue by hafiz013** [iMicknl/cordova-plugin-openalpr#20]
Hai there, this library not support for car plate from my country malaysia. Is there way to get myt.xml for my country?

**Comment by melvinversluijs** [comment]
Hi @hafiz013,

You can change the country by editing the following line of code:

Android: src/android/OpenALPR.java @ line 74
```java

Alpr alpr = new Alpr("eu", conf_file, runtime_dir);
```
iOS: src/ios/PlateScanner.mm @ line 27
```obj-c 
delegate->setCountry("eu");
```

Just change eu to whatever country you want (only countries with a corresponding xml file will work).

We would like to enhance this in the future as explained in issues https://github.com/iMicknl/cordova-plugin-openalpr/issues/2 and https://github.com/iMicknl/cordova-plugin-openalpr/issues/9

If you have any more questions feel free to ask.

Cheers,
Melvin

**Comment by iMicknl** [comment]
Questions about country support belong in the OpenALPR repository, please ask them there.
