### ISSUE TITLE
Plugin Not Fetching Data From South Africa License Plate

### ISSUE THREAD

**Issue by jainankit09** [iMicknl/cordova-plugin-openalpr#34]
Hello Friend,

I am using this plugin in my one of phonegap project for accessing data from License Plate of South Africa . i am using this code 

```javascript
cordova.plugins.OpenALPR.scan(filepath, { country: 'ZA', amount: 3 }, function (results) {
     console.log(results);
 }, function (error) {
     console.log(error.code + ': ' + error.message)
 });
```

where ZA is two letter country code for South Africa. code has been compiled successfully. But i am not able to get data after scan license plate image. I found there are many conf file present under runtime_data/config  folder for other country like eu,us,fr,gb etc. 
Please help me and let me know how can i use this . how can we manage conf file for South Africa.

Thanks in Advance!

**Comment by baukeroo** [comment]
Hi,

I 'm not sure if South Africa is already in the trained data set.
To train OpenALPR for South Africa you could take a look at: https://github.com/openalpr/train-ocr

Kind regards,
Bauke Roo

**Comment by iMicknl** [comment]
Closed due to inactivity. Please comment if the issue still persists and we will reopen.

**Comment by joshuar87** [comment]
Hi is there any progress on this? Tempted to create one using the training tessract OCR to create a ZA file. I know eu config works on some plates so might start with that file...
