### ISSUE TITLE
TypeError cannot read property 'scan' of undefined

### ISSUE THREAD

**Issue by VigilanteInc** [iMicknl/cordova-plugin-openalpr#35]
I get the error 'TypeError cannot read property 'scan' of undefined' when calling the openalpr plugin as follows

```
cordova.plugins.OpenALPR.scan(filepath, { country: 'eu', amount: 3 }, function (results) {
     console.log(results);
 }, function (error) {
     console.log(error.code + ': ' + error.message)
 });
```
installed using cordova plugin add cordova-plugin-openalpr
Android@~6.3.0

**Comment by iMicknl** [comment]
Which version of Ionic do you use?

**Comment by VigilanteInc** [comment]
Not using Ionic. 
Problem stopped after building apk.
