### ISSUE TITLE
I'm not able to use this plugin in ionic v4.

### ISSUE THREAD

**Issue by rahul-ionic** [iMicknl/cordova-plugin-openalpr#38]
I got this error after installed the plugin and trying to make the build. Please suggest me some sulution.

<details>
  <summary> Click to see full exception
BUILD FAILED in 2s
27 actionable tasks: 5 executed, 22 up-to-date
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:10: error: package com.openalpr.jni does not exist
import com.openalpr.jni.Alpr;
</summary>
BUILD FAILED in 2s
27 actionable tasks: 5 executed, 22 up-to-date
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:10: error: package com.openalpr.jni does not exist
import com.openalpr.jni.Alpr;
^
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:11: error: package com.openalpr.jni does not exist
import com.openalpr.jni.AlprException;
^
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:12: error: package com.openalpr.jni does not exist
import com.openalpr.jni.AlprPlate;
^
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:13: error: package com.openalpr.jni does not exist
import com.openalpr.jni.AlprPlateResult;
^
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:14: error: package com.openalpr.jni does not exist
import com.openalpr.jni.AlprResults;
^
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:15: error: package com.openalpr.util does not exist
import com.openalpr.util.Utils;
^
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:149: error: cannot find symbol
private Alpr initAlpr(JSONObject options, CallbackContext callbackContext) {
^
symbol: class Alpr
location: class OpenALPR
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:184: error: cannot find symbol
private JSONArray buildResponse(AlprResults results, JSONArray array) throws JSONException {
^
symbol: class AlprResults
location: class OpenALPR
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:79: error: cannot find symbol
Alpr alpr = initAlpr(options, callbackContext);
^
symbol: class Alpr
location: class OpenALPR
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:80: error: cannot find symbol
AlprResults results = null;
^
symbol: class AlprResults
location: class OpenALPR
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:85: error: cannot find symbol
} catch (AlprException e) {
^
symbol: class AlprException
location: class OpenALPR
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:114: error: cannot find symbol
Alpr alpr = initAlpr(options, callbackContext);
^
symbol: class Alpr
location: class OpenALPR
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:115: error: cannot find symbol
AlprResults results = null;
^
symbol: class AlprResults
location: class OpenALPR
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:120: error: cannot find symbol
} catch (AlprException e) {
^
symbol: class AlprException
location: class OpenALPR
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:164: error: cannot find symbol
Utils.copyAssetFolder(context.getAssets(), "runtime_data",
^
symbol: variable Utils
location: class OpenALPR
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:170: error: cannot find symbol
Alpr alpr = new Alpr(country, conf_file, runtime_dir); //Make new ALPR object with country EU and the config files from assets.
^
symbol: class Alpr
location: class OpenALPR
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:170: error: cannot find symbol
Alpr alpr = new Alpr(country, conf_file, runtime_dir); //Make new ALPR object with country EU and the config files from assets.
^
symbol: class Alpr
location: class OpenALPR
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:185: error: cannot find symbol
for (AlprPlateResult result : results.getPlates()) {
^
symbol: class AlprPlateResult
location: class OpenALPR
/Users/developer/Documents/Rahulmaurya_projects/vipark/vipark/platforms/android/app/src/main/java/org/apache/cordova/openalpr/OpenALPR.java:186: error: cannot find symbol
for (AlprPlate plate : result.getTopNPlates()) {
^
symbol: class AlprPlate
location: class OpenALPR
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
19 errors

FAILURE: Build failed with an exception.

* What went wrong:
  Execution failed for task ':app:compileDebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.

* Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org

BUILD FAILED in 2s
</details>

Please suggest something to solve this issue.

thank you in advance.

**Comment by melvinversluijs** [comment]
Hi @rahul-ionic,

Unfortunately I don't have any experience with Ionic 4, nor do I know if our plugin is compatible with it. I'll try to create a sample Ionic4 application using our plugin somewhere in the coming month.

In the mean time could you try to give us a little bit more information to help you debug your problem? 

- Which Cordova Android platform version are you using?
- How did you did you add our plugin?
- Which commands are you using to build the application?
- Does iOS work properly? 

Cheers,
Melvin
