### ISSUE TITLE
Never Hit on Ionic 4?

### ISSUE THREAD

**Issue by RZR666** [iMicknl/cordova-plugin-openalpr#43]
Hi,

I receive no error or response using Ionic 4, anyone else had an issue?

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (.nvm/versions/node/v10.4.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 6.4.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 12 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Library/Android/sdk)
   NodeJS            : v10.4.0 (/.nvm/versions/node/v10.4.0/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
```

```
public getText(imageData): Promise<any> {

    return new Promise<any>((resolve, reject) => {

      console.log("hit");

      this.openalpr.scan(imageData, this.openAlprOptions)
        .catch((err) => {

          console.error('not hit');
          reject(err)

        })
        .then((result) => 
        {
          console.log("not it");
          console.log(result);
          resolve(result);
        }
        );
    });
  }
```

**Comment by iMicknl** [comment]
- What kind of license plates are you trying to scan, could you please include an example?
- Are you using the `@ionic-native/openalpr` binding?
- What is `imageData`? Could you share a snippet of the initialisation of imageData? 

Please have a look at the [Ionic 4 sample project](https://github.com/melvinversluijs/ionic4-openalpr-sample), does this work with your image.

**Comment by RZR666** [comment]
Hi mate,

I'm trying to scan a UK Plate, [https://we.tl/t-N6Srt5N4S0](url)

I am using the Ionic Native yes.

imageData is below, which is base64, using the camera and cropperJS to toDataURL(). 

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAEBAyADAREAAhEBAxEB/8QAHwAAAQMEAwEAAAAAAAAAAAAABQMEBgIHCQoBCAsA/8QAXxAAAQMCBAMFBAYGBggDBAITAQIDEQQhBQYSMQAHQQgTIlFhCRRxgTKRobHB8AoVI0LR8RYzNFKy4RckNWJyc3SzGDZDGSUmgsInN3WTGihFU5LD0kZHVGODhKK00//EABwBAAMBAQEBAQEAAAAAAAAAAAIDBAEFAAYHCP/EAEoRAAEDAwIEAwcCBQMDAwIBDQECESEAAzFBUQQSYXGBkaEFEyKxwdHwMuEUIzNC8QZSchU0smKCwiRzJUNEUwc1Y4OiFheEkuL/2gAMAwEAAhEDEQA/AMhOYu2FlF3H15gwegocTepVuLeCzCqWUqQr3dJBDi1A6WylCVNJVqnVtBdv3/4Rdv3gJXEEvys+rsC0y57Fq7CeG90tKGckcx7gjJ1bxGuKQw/t1ZWGHVH66wesfWmqSnD6Ipp+875xaUghxTyU6VBR1K0JAgkiRfi8GjiedSuYQeUAuXCjJ1xg9G1NM4h+UID9xl8k4jIbOMVbbPPbfwbGMbo6Nz3NtnB2V1QpGS4CkOtKQG3KppAaDgUYA1OIICrxB4+o4ZF62U8xCnDdA86fL7VzOJQUWjyvzkOAXGRD4y7/AHFWxwX2hWJUTqqjL+WMODLdUtpdQ6+pFQpQVoDhdTd0BGkFUSUhIm1h42yq4sC4QLZHxgFsCIbfr0gZr9kW1i2v35JJgP0diS4zMiXFSTLXbiy9i2bqqsz9gjlRUam3qWooagqpGNCAmEqcKlMobSQpQ7shSgZGpQIitov8PaX7tTIMKbKZGCR2nrincQE8xBcpwOud....

I have based this on the Ionic 4 sample, so it should be the same but I'm getting no result and no error.

**Comment by RZR666** [comment]
`java.lang.ClassNotFoundException: org.apache.cordova.openalpr.OpenALPR
04-12 08:27:55.117  9138  9273 W System.err: 	at java.lang.Class.classForName(Native Method)
04-12 08:27:55.118  9138  9273 W System.err: 	at java.lang.Class.forName(Class.java:453)
04-12 08:27:55.118  9138  9273 W System.err: 	at java.lang.Class.forName(Class.java:378)
04-12 08:27:55.118  9138  9273 W System.err: 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
04-12 08:27:55.119  9138  9273 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
04-12 08:27:55.120  9138  9273 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
04-12 08:27:55.121  9138  9273 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
04-12 08:27:55.124  9138  9273 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
04-12 08:27:55.124  9138  9273 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-12 08:27:55.125  9138  9273 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:325)
04-12 08:27:55.125  9138  9273 W System.err: 	at android.os.Looper.loop(Looper.java:142)
04-12 08:27:55.125  9138  9273 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
04-12 08:27:55.126  9138  9273 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.cordova.openalpr.OpenALPR" on path: DexPathList[[zip file "/data/app/uk.co.psattendant-obCaLQ7CGJTbUyQHYVw7EA==/base.apk"],nativeLibraryDirectories=[/data/app/uk.co.psattendant-obCaLQ7CGJTbUyQHYVw7EA==/lib/arm64, /data/app/uk.co.psattendant-obCaLQ7CGJTbUyQHYVw7EA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
04-12 08:27:55.126  9138  9273 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
04-12 08:27:55.127  9138  9273 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-12 08:27:55.127  9138  9273 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-12 08:27:55.127  9138  9273 W System.err: 	... 12 more
04-12 08:27:55.128  9138  9273 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
04-12 08:27:55.129  9138  9273 W System.err: 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
04-12 08:27:55.129  9138  9273 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
04-12 08:27:55.129  9138  9273 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
04-12 08:27:55.129  9138  9273 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
04-12 08:27:55.130  9138  9273 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-12 08:27:55.130  9138  9273 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:325)
04-12 08:27:55.130  9138  9273 W System.err: 	at android.os.Looper.loop(Looper.java:142)
04-12 08:27:55.130  9138  9273 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
`

This is the logcat.

**Comment by RZR666** [comment]
Ok, so I removed everything, and added the android version used in your Sample and I have a different error...

`  "dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/pwa": "^0.12.4",
    "@angular/router": "^7.2.2",
    "@angular/service-worker": "^7.2.2",
    "@ionic-native/camera-preview": "^5.4.0",
    "@ionic-native/core": "^5.4.0",
    "@ionic-native/http": "^5.4.0",
    "@ionic-native/openalpr": "^5.4.0",
    "@ionic-native/splash-screen": "^5.4.0",
    "@ionic-native/status-bar": "^5.4.0",
    "@ionic/angular": "^4.2.0",
    "@ionic/storage": "^2.2.0",
    "cordova-android": "7.1.4",
    "cordova-plugin-camera-preview": "0.10.0",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^4.0.1",
    "cordova-plugin-openalpr": "^2.1.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "3.2.0",
    "core-js": "^2.5.4",   
"ngx-cropperjs": "^0.1.9",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.29"
  },`

`04-12 09:38:15.195 22007 22116 W System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/uk.co.psattendant-QixE7lNhSE1_mp10sRDNFw==/base.apk"],nativeLibraryDirectories=[/data/app/uk.co.psattendant-QixE7lNhSE1_mp10sRDNFw==/lib/arm64, /data/app/uk.co.psattendant-QixE7lNhSE1_mp10sRDNFw==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libopenalprjni.so"
04-12 09:38:15.196 22007 22116 W System.err: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
04-12 09:38:15.196 22007 22116 W System.err: 	at java.lang.System.loadLibrary(System.java:1657)
04-12 09:38:15.196 22007 22116 W System.err: 	at com.openalpr.jni.Alpr.<clinit>(Alpr.java:9)
04-12 09:38:15.196 22007 22116 W System.err: 	at org.apache.cordova.openalpr.OpenALPR.initAlpr(OpenALPR.java:170)
04-12 09:38:15.196 22007 22116 W System.err: 	at org.apache.cordova.openalpr.OpenALPR.scan(OpenALPR.java:114)
04-12 09:38:15.197 22007 22116 W System.err: 	at org.apache.cordova.openalpr.OpenALPR.execute(OpenALPR.java:44)
04-12 09:38:15.197 22007 22116 W System.err: 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
04-12 09:38:15.197 22007 22116 W System.err: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
04-12 09:38:15.197 22007 22116 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
04-12 09:38:15.197 22007 22116 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
04-12 09:38:15.197 22007 22116 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-12 09:38:15.197 22007 22116 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:325)
04-12 09:38:15.198 22007 22116 W System.err: 	at android.os.Looper.loop(Looper.java:142)
04-12 09:38:15.198 22007 22116 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
`

**Comment by RZR666** [comment]
so tried it on another phone and this one gets further ....

`D/SystemWebChromeClient( 5971): http://192.168.1.166:8100/main.js: Line 2059 : Start Scanning Reg.
I/chromium( 5971): [INFO:CONSOLE(2059)] "Start Scanning Reg.", source: http://192.168.1.166:8100/main.js (2059)
D/HeadsetStateMachine( 2733): Disconnected process message: 10, size: 0
W/PluginManager( 5971): THREAD WARNING: exec() call to OpenALPR.scan blocked the main thread for 632ms. Plugin should use CordovaInterface.getThreadPool().
D/SystemWebChromeClient( 5971): http://192.168.1.166:8100/main.js: Line 2062 : Reg Result.
I/chromium( 5971): [INFO:CONSOLE(2062)] "Reg Result.", source: http://192.168.1.166:8100/main.js (2062)
D/SystemWebChromeClient( 5971): http://192.168.1.166:8100/main.js: Line 2063 : 
I/chromium( 5971): [INFO:CONSOLE(2063)] "", source: http://192.168.1.166:8100/main.js (2063)
D/SystemWebChromeClient( 5971): http://192.168.1.166:8100/main.js: Line 2068 : Reg Error.
I/chromium( 5971): [INFO:CONSOLE(2068)] "Reg Error.", source: http://192.168.1.166:8100/main.js (2068)
D/SystemWebChromeClient( 5971): http://192.168.1.166:8100/main.js: Line 2069 : TypeError: Cannot read property 'number' of undefined
I/chromium( 5971): [INFO:CONSOLE(2069)] "TypeError: Cannot read property 'number' of undefined", source: http://192.168.1.166:8100/main.js (2069)
D/audio_hw_primary(  240): out_standby: enter: stream (0xb5880740) usecase(1: low-latency-playback)
`

**Comment by melvinversluijs** [comment]
Hi @RZR666,

We've only built the library for armeabi-v7a since most Android devices seem to support this. However the default Android Studio recommended images seem to be x86. While creating an emulator using Android Studio you can choose the 'Other Images' tab to select an armeai-v7a image.

I've also tried the image you've included using our ionic-4-sample application and this one did not seem to work. I'm guessing this is because it is a cutout on a white background, which the OpenALPR library probably is not trained for. When I used a Google Image of an UK license (one on an actual car) it did work.

If you are not sure if the plugin is being triggered you could always try to use the Android Studio debugger. Adding a breakpoint to the start of the org.apache.cordova/OpenALPR file should help you out a bit.

Cheers, Melvin

**Comment by RZR666** [comment]
Cheers mate.

This was running on an actual device, I've since tried another phone and it worked great so I guess it's limited to certain devices.

**Comment by RZR666** [comment]
Found the lib on this repo for anyone with the same issue...

https://github.com/ptrstovka/openalpr-android

**Comment by iMicknl** [comment]
Great to hear @RZR666. I will close this issue. If you made modifications to enable support on arm64, could you do a pull request to contribute back?

**Comment by RZR666** [comment]
Hi, 

If I get it working I will update.

It's not working on most Android phones at present, I've found all the libs at another repo below,

https://github.com/BabbleCar/cordova-plugin-scanplate

But it looks like libopenalprjni.so needs compiling for each architechture.

**Comment by Dullaz** [comment]
Faced this issue, managed to fix it so it runs off my phone, not emulator.

Emulators are (most of the time) x86. This plugin is specifically build around armeabi-v7a. 
90%+ of android phones support armeabi-v7a. 

The fix I found is putting the following configuration in your **app build.grade**, inside the **android block**

`ndk {
            abiFilters "armeabi-v7a"
        }`

This will force the host device to run the apk only for this architecture and not look for any other libraries anywhere else.
