### ISSUE TITLE
openalpr.conf changes not being picked up when app built

### ISSUE THREAD

**Issue by kevshub** [iMicknl/cordova-plugin-openalpr#50]
Tweaking settings in

`/plugins/cordova-plugin-openalpr/src/openalpr.conf`

are not being picked up when  `cordova build ios` is ran.

I'm getting 'runtime_dir is not defined' which initially encouraged me to add

`runtime_dir = ${CMAKE_INSTALL_PREFIX}/share/openalpr/runtime_data`

to the file based on another issue raised here, however that, and other tweaks I'm making in an effort to try and make the readings more accurate are having no effect on the plugin. I want to enable pattern matching to negate 1's being picked up as I's and having dug through the code I know what I need to know but it doesnt appear to taking the config info.

**Comment by kevshub** [comment]
I always find the answer after I post! for anyone else that has this issue open

`openalpr.conf file in xcode (Located: Resources/openalpr.conf)`

You'll more than likely find your changes havent been saved, change them here and you're good to go!

**Comment by iMicknl** [comment]
Feel free to do a PR, to change the scripts to use just one openalpr.conf file. :-)
