### ISSUE TITLE
Add Android support

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/cordova-plugin-openalpr#7]

**Comment by iMicknl** [comment]
Current status:
- [x] Create basic Android integration
- [ ] Compile OpenALPR JNI libraries and include them in plugin

(branch: [feature/android-openalpr](https://github.com/iMicknl/cordova-plugin-openalpr/tree/feature/android-openalpr))
feature/android-openalpr

**Comment by m3lv1n** [comment]
Added OpenALPR JNI Libraries
